logo: # add logo name
title: RCO Art
description: > # this means to ignore newlines until "baseurl:"
  Art projects webpage.
permalink: ':title/'
baseurl: "/" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Banner settings
video: home6.png # add banner video. Add your video file to the folder video
banner-title: RCO Art # add banner title
banner-desc: (under development) # add banner description

# Author settings
author-pic: face.jpg # your photo
author-name: Romina Cristi Olate # your name
about-author: # about author
email: your-email@domain.com # your email
phone: # your pnone number
website: http://rco.space # you website

# Social link
google_url:    # add url link
twitter_url:   # add url link 
instagram_url: # add url link
pinterest_url: # add url link
dribbble_url:  # add url link
facebook_url:  # add url link

# Disqus
discus_identifier: mr-brown # add your discus identifier

# Newsletter
mailchimp: # add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e

# Tracker
analytics:

# Paginate
paginate: 12
paginate_path: /page:num/

# Build settings
markdown: kramdown
plugins:
  - jekyll-paginate
  - jekyll-sitemap

include: [_pages]
exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
